This notebook is an example on how to import the function in utils (`retrieve_categories` in particular)

In [1]:
import os

os.chdir('..')
cwd = os.getcwd()

In [2]:
import pandas as pd
import json

data_dir = '/data/'

In [3]:
movie_details_neat = pd.read_pickle(cwd + data_dir + 'pre-processed/movie_details_neat.pkl')

movie_details_neat.head()

,budget,id,popularity,revenue,runtime,vote_average,vote_count,genres,keywords,original_language,original_title,overview,production_companies,production_countries,release_date,spoken_languages,movie_id,cast,crew
0,105000000,64682,61.196071,351040419,143.0,7.3,3769,"{'id': [18, 10749], 'name': ['Drama', 'Romance']}","{'id': [818, 1326, 1523, 3929, 209714], 'name'...",en,The Great Gatsby,An adaptation of F. Scott Fitzgerald's Long Is...,"{'name': ['Village Roadshow Pictures', 'Bazmar...","{'iso_3166_1': ['US', 'AU'], 'name': ['United ...",2013-05-10,"{'iso_639_1': ['en'], 'name': ['English']}",64682,"{'cast_id': [2, 5, 3, 8, 6, 4, 7, 22, 13, 23, ...","{'credit_id': ['52fe46e3c3a368484e0a982d', '52..."
1,150000000,9543,62.169881,335154643,116.0,6.2,2317,"{'id': [12, 14, 28, 10749], 'name': ['Adventur...","{'id': [1241, 1965, 12653, 12654, 12655, 41645...",en,Prince of Persia: The Sands of Time,A rogue prince reluctantly joins forces with a...,"{'name': ['Walt Disney Pictures', 'Jerry Bruck...","{'iso_3166_1': ['US'], 'name': ['United States...",2010-05-19,"{'iso_639_1': ['en'], 'name': ['English']}",9543,"{'cast_id': [5, 2, 7, 4, 6, 8, 9, 10, 26, 27, ...","{'credit_id': ['567e74d4c3a36860e9008e46', '52..."
2,140000000,5174,22.571780,258022233,91.0,6.1,783,"{'id': [28, 35, 80, 53], 'name': ['Action', 'C...","{'id': [1704], 'name': ['ambassador']}",en,Rush Hour 3,After an attempted assassination on Ambassador...,"{'name': ['New Line Cinema'], 'id': [12]}","{'iso_3166_1': ['US'], 'name': ['United States...",2007-08-08,"{'iso_639_1': ['la', 'en', 'fr', 'ja', 'zh'], ...",5174,"{'cast_id': [2, 3, 4, 5, 6, 7, 8, 9, 26, 27, 2...","{'credit_id': ['52fe43fac3a36847f807b5bd', '52..."
3,145000000,1735,60.034162,401128639,112.0,5.2,1387,"{'id': [12, 28, 14], 'name': ['Adventure', 'Ac...",{},en,The Mummy: Tomb of the Dragon Emperor,"Archaeologist Rick O'Connell travels to China,...","{'name': ['Universal Pictures', 'China Film Co...","{'iso_3166_1': ['DE', 'US'], 'name': ['Germany...",2008-07-01,"{'iso_639_1': ['en', 'zh', 'sa'], 'name': ['En...",1735,"{'cast_id': [1, 2, 8, 12, 13, 14, 15, 16, 17, ...","{'credit_id': ['52fe4312c3a36847f80384c5', '52..."
4,27000000,79698,2.418535,0,109.0,4.8,34,"{'id': [28, 12, 878, 10749], 'name': ['Action'...",{},en,The Lovers,The Lovers is an epic romance time travel adve...,"{'name': ['Corsan', 'Bliss Media', 'Limelight ...","{'iso_3166_1': ['AU', 'BE', 'IN'], 'name': ['A...",2015-02-13,"{'iso_639_1': ['en'], 'name': ['English']}",79698,"{'cast_id': [11, 13, 22, 17, 14, 15, 16, 18, 1...","{'credit_id': ['52fe49e0c3a368484e145067', '57..."

In [20]:
with open(cwd + data_dir + 'pre-processed/id_maps.json', 'r') as f:
    id_maps = json.load(f)

Example on how to import the function

In [15]:
import sys
sys.path.insert(0, os.path.abspath(cwd + '/utils/'))

from util import retrieve_category

In [19]:
drama_row = retrieve_category(movie_details_neat, column_name='genres', ids=18, id_key_name='id', id_maps=id_maps)

drama_row.head()

,budget,id,popularity,revenue,runtime,vote_average,vote_count,genres,keywords,original_language,original_title,overview,production_companies,production_countries,release_date,spoken_languages,movie_id,cast,crew
0,105000000,64682,61.196071,351040419,143.0,7.3,3769,"{'id': [18, 10749], 'name': ['Drama', 'Romance']}","{'id': [818, 1326, 1523, 3929, 209714], 'name'...",en,The Great Gatsby,An adaptation of F. Scott Fitzgerald's Long Is...,"{'name': ['Village Roadshow Pictures', 'Bazmar...","{'iso_3166_1': ['US', 'AU'], 'name': ['United ...",2013-05-10,"{'iso_639_1': ['en'], 'name': ['English']}",64682,"{'cast_id': [2, 5, 3, 8, 6, 4, 7, 22, 13, 23, ...","{'credit_id': ['52fe46e3c3a368484e0a982d', '52..."
1,15000000,315011,9.476999,77000000,120.0,6.5,143,"{'id': [28, 12, 18, 27, 878], 'name': ['Action...","{'id': [1299, 7671, 11100, 14796, 161791, 2355...",ja,シン・ゴジラ,From the mind behind Evangelion comes a hit la...,"{'name': ['Cine Bazar', 'Toho Pictures'], 'id'...","{'iso_3166_1': ['JP'], 'name': ['Japan']}",2016-07-29,"{'iso_639_1': ['it', 'de', 'en', 'ja'], 'name'...",315011,"{'cast_id': [4, 2, 3, 5, 50, 10, 84, 24, 29, 2...","{'credit_id': ['5921d321c3a368799b05933f', '59..."
2,150000000,4922,60.269279,333932083,166.0,7.3,3292,"{'id': [14, 18, 53, 9648, 10749], 'name': ['Fa...","{'id': [2913, 3588, 3739, 4262, 9935, 11612], ...",en,The Curious Case of Benjamin Button,"Tells the story of Benjamin Button, a man who ...","{'name': ['Paramount Pictures', 'Warner Bros.'...","{'iso_3166_1': ['US'], 'name': ['United States...",2008-11-24,"{'iso_639_1': ['en'], 'name': ['English']}",4922,"{'cast_id': [4, 5, 6, 10, 7, 183, 8, 9, 11, 13...","{'credit_id': ['52fe43e2c3a36847f8076327', '52..."
3,150000000,27022,35.580815,215283742,109.0,5.8,1470,"{'id': [14, 12, 28, 35, 18], 'name': ['Fantasy...","{'id': [616, 657, 1994, 2098, 2343, 3096, 3098...",en,The Sorcerer's Apprentice,Balthazar Blake is a master sorcerer in modern...,"{'name': ['Walt Disney Pictures', 'Jerry Bruck...","{'iso_3166_1': ['US'], 'name': ['United States...",2010-07-13,"{'iso_639_1': ['en'], 'name': ['English']}",27022,"{'cast_id': [4, 5, 6, 7, 9, 10, 11, 18, 13, 14...","{'credit_id': ['52fe4528c3a368484e04b981', '56..."
4,150000000,7978,21.214571,0,102.0,5.5,549,"{'id': [18, 27, 53], 'name': ['Drama', 'Horror...","{'id': [494, 8250, 9714, 11004, 12564], 'name'...",en,The Wolfman,"Lawrence Talbot, an American man on a visit to...","{'name': ['Universal Pictures', 'Stuber Produc...","{'iso_3166_1': ['US'], 'name': ['United States...",2010-02-11,"{'iso_639_1': ['en'], 'name': ['English']}",7978,"{'cast_id': [3, 2, 7, 8, 9, 10, 13, 15, 16, 18...","{'credit_id': ['538aeb0a0e0a266718000fc2', '53..."