# ML-Prediction ANN

In [1]:
import pandas as pd
import numpy as np
import os
import json
from collections import Counter
from sklearn.preprocessing import MultiLabelBinarizer
import sys

In [16]:
import sys
sys.path.insert(0, os.path.abspath('../utils/')) #point this to the where util is relatively to your working directory
from util import *

data_dir = get_path_to_data_dir()
print(data_dir) #check that it's correct

/Users/admin/Documents/Jobs/Datatonic/datatonic-challenge/data/

In [17]:
#loading the data from the pickled file
movie_data = pd.read_pickle(data_dir + 'pre-processed/movie_encoded_only_numeric.pkl')

In [18]:
movie_data

,budget,id,revenue,runtime,vote_average,vote_count,release_date,lead_male,lead_female,lead2_male,...,Yasiin Bey,Yul Vazquez,Zac Efron,Zach Galifianakis,Zachary Woodlee,Zak Penn,Zeljko Ivanek,Zhang Ziyi,Zoe Saldana,Zooey Deschanel
0,105000000,64682,351040419,143.0,7.3,3769,130,1,0,1,...,0,0,0,0,0,0,0,0,0,0
1,150000000,9543,335154643,116.0,6.2,2317,139,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,140000000,5174,258022233,91.0,6.1,783,220,1,0,1,...,0,0,0,0,0,0,0,0,0,0
3,145000000,1735,401128639,112.0,5.2,1387,183,1,0,1,...,0,0,0,0,0,0,0,0,0,0
4,15000000,315011,77000000,120.0,6.5,143,211,1,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3069,14000000,33693,76901,85.0,6.3,8,263,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3070,12000,692,6000000,93.0,6.2,110,72,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3071,20000,36095,99000,111.0,7.4,63,310,1,0,1,...,0,0,0,0,0,0,0,0,0,0
3072,7000,14337,424760,77.0,6.9,658,282,1,0,1,...,0,0,0,0,0,0,0,0,0,0
3073,220000,9367,2040920,81.0,6.6,238,248,1,0,0,...,0,0,0,0,0,0,0,0,0,0

### Normalise the data
The initial data.describe() for `'budget', 'revenue', 'runtime', 'release_date'` shows the extreme jump from the 75% confidence interval to the maximum value.  Even with the removal of the z values exceeding 3 stds, budget requires transformation.

##### Normalising function

In [25]:
def normalize(column):
    upper = column.max()
    lower = column.min()
    y = (column - lower)/(upper-lower)
    return y

In [26]:
for column in columns_to_scale:
    movie_data = normalize(column, movie_data)
movie_data.describe()

UFuncTypeError: ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U21'), dtype('<U21')) -> dtype('<U21')

In [20]:
def feature_scaling(column, df):
    cube_root = df[column]**(1/3)
    cube_norm = normalize(cube_root)
    df[column+"_cube_norm"] = cube_norm
    
    return df

columns_to_scale = ['budget', 'revenue', 'runtime', 'release_date']
for column in columns_to_scale:
    movie_data = feature_scaling(column, movie_data)

Here if we scroll to the left then we can see that these cobe norm variables have been produced.

In [21]:
movie_data

,budget,id,revenue,runtime,vote_average,vote_count,release_date,lead_male,lead_female,lead2_male,...,Zachary Woodlee,Zak Penn,Zeljko Ivanek,Zhang Ziyi,Zoe Saldana,Zooey Deschanel,budget_cube_norm,revenue_cube_norm,runtime_cube_norm,release_date_cube_norm
0,105000000,64682,351040419,143.0,7.3,3769,130,1,0,1,...,0,0,0,0,0,0,0.887693,0.853630,0.834416,0.661474
1,150000000,9543,335154643,116.0,6.2,2317,139,1,0,0,...,0,0,0,0,0,0,1.000000,0.840522,0.669359,0.680071
2,140000000,5174,258022233,91.0,6.1,783,220,1,0,1,...,0,0,0,0,0,0,0.977222,0.770174,0.491777,0.819451
3,145000000,1735,401128639,112.0,5.2,1387,183,1,0,1,...,0,0,0,0,0,0,0.988742,0.892533,0.642789,0.760979
4,15000000,315011,77000000,120.0,6.5,143,211,1,0,1,...,0,0,0,0,0,0,0.463148,0.513987,0.695324,0.805871
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3069,14000000,33693,76901,85.0,6.3,8,263,0,0,0,...,0,0,0,0,0,0,0.452576,0.049510,0.444408,0.879671
3070,12000,692,6000000,93.0,6.2,110,72,1,0,0,...,0,0,0,0,0,0,0.041284,0.218348,0.507103,0.514135
3071,20000,36095,99000,111.0,7.4,63,310,1,0,1,...,0,0,0,0,0,0,0.049298,0.054041,0.636048,0.938393
3072,7000,14337,424760,77.0,6.9,658,282,1,0,1,...,0,0,0,0,0,0,0.034185,0.089110,0.377645,0.904191
3073,220000,9367,2040920,81.0,6.6,238,248,1,0,0,...,0,0,0,0,0,0,0.111946,0.151793,0.411576,0.859465