## EDA - are sequels and films made after books more successful?

In [1]:
#getting the dir 
import os
os.chdir('..')
cwd = os.getcwd()

In [2]:
import pandas as pd
import json 
data_dir = '/data/'

In [3]:
movie_details_neat = pd.read_pickle(cwd + data_dir + 'pre-processed/movie_details_neat.pkl')

movie_details_neat.head()

,budget,id,popularity,revenue,runtime,vote_average,vote_count,genres,keywords,original_language,original_title,overview,production_companies,production_countries,release_date,spoken_languages,movie_id,cast,crew
0,105000000,64682,61.196071,351040419,143.0,7.3,3769,"{'id': [18, 10749], 'name': ['Drama', 'Romance']}","{'id': [818, 1326, 1523, 3929, 209714], 'name'...",en,The Great Gatsby,An adaptation of F. Scott Fitzgerald's Long Is...,"{'name': ['Village Roadshow Pictures', 'Bazmar...","{'iso_3166_1': ['US', 'AU'], 'name': ['United ...",2013-05-10,"{'iso_639_1': ['en'], 'name': ['English']}",64682,"{'cast_id': [2, 5, 3, 8, 6, 4, 7, 22, 13, 23, ...","{'credit_id': ['52fe46e3c3a368484e0a982d', '52..."
1,150000000,9543,62.169881,335154643,116.0,6.2,2317,"{'id': [12, 14, 28, 10749], 'name': ['Adventur...","{'id': [1241, 1965, 12653, 12654, 12655, 41645...",en,Prince of Persia: The Sands of Time,A rogue prince reluctantly joins forces with a...,"{'name': ['Walt Disney Pictures', 'Jerry Bruck...","{'iso_3166_1': ['US'], 'name': ['United States...",2010-05-19,"{'iso_639_1': ['en'], 'name': ['English']}",9543,"{'cast_id': [5, 2, 7, 4, 6, 8, 9, 10, 26, 27, ...","{'credit_id': ['567e74d4c3a36860e9008e46', '52..."
2,140000000,5174,22.571780,258022233,91.0,6.1,783,"{'id': [28, 35, 80, 53], 'name': ['Action', 'C...","{'id': [1704], 'name': ['ambassador']}",en,Rush Hour 3,After an attempted assassination on Ambassador...,"{'name': ['New Line Cinema'], 'id': [12]}","{'iso_3166_1': ['US'], 'name': ['United States...",2007-08-08,"{'iso_639_1': ['la', 'en', 'fr', 'ja', 'zh'], ...",5174,"{'cast_id': [2, 3, 4, 5, 6, 7, 8, 9, 26, 27, 2...","{'credit_id': ['52fe43fac3a36847f807b5bd', '52..."
3,145000000,1735,60.034162,401128639,112.0,5.2,1387,"{'id': [12, 28, 14], 'name': ['Adventure', 'Ac...",{},en,The Mummy: Tomb of the Dragon Emperor,"Archaeologist Rick O'Connell travels to China,...","{'name': ['Universal Pictures', 'China Film Co...","{'iso_3166_1': ['DE', 'US'], 'name': ['Germany...",2008-07-01,"{'iso_639_1': ['en', 'zh', 'sa'], 'name': ['En...",1735,"{'cast_id': [1, 2, 8, 12, 13, 14, 15, 16, 17, ...","{'credit_id': ['52fe4312c3a36847f80384c5', '52..."
4,27000000,79698,2.418535,0,109.0,4.8,34,"{'id': [28, 12, 878, 10749], 'name': ['Action'...",{},en,The Lovers,The Lovers is an epic romance time travel adve...,"{'name': ['Corsan', 'Bliss Media', 'Limelight ...","{'iso_3166_1': ['AU', 'BE', 'IN'], 'name': ['A...",2015-02-13,"{'iso_639_1': ['en'], 'name': ['English']}",79698,"{'cast_id': [11, 13, 22, 17, 14, 15, 16, 18, 1...","{'credit_id': ['52fe49e0c3a368484e145067', '57..."

There are three variables provided in the dataset that can help is define success:
- Revenue
- Popularity
- Rating
We are assuming that revenue is calculated in $, and rating is assigned the average rating from all votes. The popularity of a movie is an index calculated from the variables listed in the [link provided](https://developers.themoviedb.org/3/getting-started/popularity "Popularity scoring explained"). We will use all three in identifying whether sequels or movies based on books are more successful.

In [4]:
with open(cwd + data_dir + 'pre-processed/id_maps.json', 'r') as f:
    id_maps = json.load(f)

In [ ]:
book_rows = retrieve_category(movie_details_neat, 'keywords', 18, 'id', '', id_maps)

drama_rows.head()

In [6]:
def retrieve_category(df, column_name, ids, id_key_name, result_file_name='', id_maps=None):
    result = df[df.apply(lambda row: False if id_key_name not in row[column_name].keys() else (ids in (row[column_name][id_key_name])), axis=1)]
    if not result_file_name:
        if id_maps:
            result_file_name = column_name + '_' + id_maps[column_name][str(ids)]
        else:
            result_file_name = column_name + '_' + str(ids)
    #result.to_pickle(cwd + data_dir + 'pre-processed/' + result_file_name + '.pkl')
    return result

The potential properties associated with high popularity/rating movies can be runtime, budget, cast, director, keywords, genres, production companies. In the dataset, these data are classified as two types: quantitative data and categorical data. Both runtime and budget data are quantitative data; the others are categorical data.